### ISSUE TITLE
How to send file with xmpppy?

### ISSUE THREAD

**Issue by pythonshiva** [xmpppy/xmpppy#21]
How can i transfer a file(text file or image file) through xmpppy

**Comment by snakeru** [comment]
I do not know if that is possible yet. There was some code, that
implemented in-band *data* transfer, but for *file* transfer you also need
signalling.
Am 23.02.2015 07:40 schrieb "pythonshiva" <notifications@github.com>:

**Comment by pythonshiva** [comment]
Hi @snakeru Thanks for reply, I have found "filetransfer.py" in your xmpp folder. How to use that for transferring a file.

**Comment by snakeru** [comment]
Hi.

See my previous answer :)
Or, alternatively, check out the source.
Am 23.02.2015 08:40 schrieb "pythonshiva" <notifications@github.com>:

**Comment by amotl** [comment]
Dear @pythonshiva,

the inline documentation for the `filetransfer.py` module says:
> This module contains IBB class that is the simple implementation of XEP-0047.
> Note that this is just a transport for data. You have to negotiate data transfer before (via StreamInitiation most probably). Unfortunately SI is not implemented yet.

Alternatively, you might want to look at the corresponding implementations of XEP-0047 at [1] or [2]. Therefore, I believe it is safe to close this issue. Feel free to reopen if you have further questions.

With kind regards,
Andreas.

[1] https://github.com/poezio/slixmpp/blob/master/docs/api/plugins/xep_0047.rst
[2] https://github.com/horazont/aioxmpp/pull/247
