### ISSUE TITLE
Execute ejabberdctl commands

### ISSUE THREAD

**Issue by gathole** [xmpppy/xmpppy#26]
Is there any way to execute ejabberdctl commands and get the results using XMPPPY library?

Example: If I want to get current offline messages for a user, I can run `ejabberdctl get_offline_count user server` command on server. How can I get the same using XMPPPY library?

**Comment by amotl** [comment]
Dear Satish,

this is a very late answer to your question, apologies. I believe this kind of feature is out of scope for this library and will never by implemented. So, I am closing this issue.

With kind regards,
Andreas.

**Comment by normanr** [comment]
It doesn't look like `get_offline_count` is available via xmpp. It's a `mod_http_api` command, and `mod_http_api` only seems to be available via an http api. Some of the `mod_http_api` commands are _also_ available via `mod_announce` and `mod_configure` (like `change_password` as `change-user-password`), but there's not a lot of overlap.
