### ISSUE TITLE
Patch for SSL/TLS communication

### ISSUE THREAD

**Issue by SHFRGRP** [xmpppy/xmpppy#27]
Fix error with `tcpsock._sslObj.issuer()`.

https://raw.githubusercontent.com/freebsd/freebsd-ports/master/net-im/py-xmpppy/files/patch-xmpp-transports.py

**Comment by amotl** [comment]
Dear @SHFRGRP,

we just released version 0.6.0 which has this fix and might also be ready for Python3. May I humbly ask you whether you are involved with the FreeBSD community and might be able to trigger an update?

With kind regards,
Andreas.

**Comment by amotl** [comment]
> we just released version 0.6.0 which has this fix and might also be ready for Python3

Just for the records: It probably was 73d5f9b3, contributed by @osminogin the other day.

I believe it is safe to close this issue.
