### ISSUE TITLE
Move other parts in this org?

### ISSUE THREAD

**Issue by Neustradamus** [xmpppy/xmpppy#33]
@normanr: Can you move other repositories too?
- https://github.com/normanr/skype-transport
- https://github.com/normanr/irc-transport
- https://github.com/normanr/yahoo-transport
- https://github.com/normanr/mxit-transport
- https://github.com/normanr/myspace-transport
- https://github.com/normanr/mail-transport

You can move too: https://github.com/normanr/xmppd?

I think that I have forgotten nothing.

**Comment by normanr** [comment]
I think I got them all :smile:

**Comment by Neustradamus** [comment]
@normanr: Thanks a lot :)
