### ISSUE TITLE
auth.py type error setTagData('digest')

### ISSUE THREAD

**Issue by smudge1977** [xmpppy/xmpppy#38]
Line 58 has a type error as sha1 needs a bytes so have wrapped in an encode('utf-8') to fix
```
query.setTagData('digest',sha1((owner.Dispatcher.Stream._document_attrs['id']+self.password).encode('utf-8')).hexdigest())
```

**Comment by Neustradamus** [comment]
@smudge1977: All SCRAM are not supported, it is the most important missing feature.

Note: DIGEST-MD5 is obsolete.

Linked to:
- https://github.com/xmpppy/xmpppy/issues/32

**Comment by amotl** [comment]
Hi there,

thank you for creating #32 on this topic, @Neustradamus. Also, thanks for educating us about that the `digest` authentication is obsolete already.

Still, may I ask @smudge1977 again if he would actually need this to be fixed anyway, maybe for any kinds of archaeological purposes? If so, maybe you could submit a pull request?

With kind regards,
Andreas.

**Comment by smudge1977** [comment]
Sorry just tested 
https://github.com/xmpppy/xmpppy/commit/e12316d1fb8e61ecaa45bb6548c77be46a984c56
and this works fine for me - thanks
