### ISSUE TITLE
xmpp-message does not allow jid/pw to be in a file

### ISSUE THREAD

**Issue by gdt** [xmpppy/xmpppy#42]
With xsend.py, one puts JID and PASSWORD in ~/.xsend, and that allows keeping credentials separate from scripts (which might be checked in).   Because of this, xmpp-message almost replaces xsend.py, but not quite.

**Comment by amotl** [comment]
Dear Greg,

thanks for writing in and sorry for the delay. #55 implements your request.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I've just released xmpppy version 0.7.0, including this patch. Please let me know if you observe any issues.

With kind regards,
Andreas.

**Comment by gdt** [comment]
Just to close the loop:  i have locally updated pkgsrc to 0.7.0 (will commit after we unfreeze, not an xmpppy issue), and xmpp-message works fine with the .xsend I had with xsend.py, once I read the help text and added the long options to my invocation.   So I'm happily using this with Python 3.9, with no local mods.
