### ISSUE TITLE
Using the basic.py script, where should its destination be sent to?

### ISSUE THREAD

**Issue by higher75** [xmpppy/xmpppy#44]
Excuse me, should I build an xmpp server for testing?
What kind of service should ubuntu18.04 build?

Using the basic.py script, where should its destination be sent to?
Are the required passwords and user names already set when the service is set up?

thanks you!

**Comment by amotl** [comment]
Dear @higher75,

the arguments to the `basic.py` program have to be given on the command line, separated by space characters.

The order of the arguments is:
```python
sender, password, receiver, message = sys.argv[1:5]
```

With kind regards,
Andreas.

[1] https://github.com/xmpppy/xmpppy/blob/master/docs/examples/basic.py
