### ISSUE TITLE
Error handling is not correct (at least under Windows)

### ISSUE THREAD

**Issue by oxivanisher** [xmpppy/xmpppy#49]
During debugging of another problem, I stumbled upon the following error:
While trying to connect, the line [165 in `transports.py`](https://github.com/xmpppy/xmpppy/blob/db73250d5f8df24737e063c089e6d452e35116e1/xmpp/transports.py#L165) is failing, since the `socket.error` has a tuple with five elements but the current code only supports two. I do not know if the number of elements is different only between operating systems or depending on the error, but it should be able to handle all errors. Mine was:
![image](https://user-images.githubusercontent.com/264994/137935023-896fcc7f-1c6f-45ca-8db3-398177a3c86f.png)

```python
  File "xxx\lib\site-packages\xmpp\transports.py", line 166, in connect
    (errno, strerror) = xxx_todo_changeme.args
ValueError: too many values to unpack (expected 2)
```

**Comment by amotl** [comment]
Dear Marc,

thanks for your report. The origin of this error is most probably that the code base has originally been conceived for Python 2 und still aims to be compatible with it. It doesn't see many improvements, but we are still regularily publishing bugfix releases.

~~So, can I humbly ask you to submit a corresponding patch? We will be happy to turn that into a release without further ado.~~ Can I ask you to try if the patch from #50 already resolves the issue for you?

With kind regards,
Andreas.
