### ISSUE TITLE
authentication failure with python3.8, but works with python2.7

### ISSUE THREAD

**Issue by gdt** [xmpppy/xmpppy#52]
I am trying to use 0.6.3 on NetBSD against ejabberd.   When built with python2.7, using the provided xsend.py example script works fine.   When I build with ptyhon3.8, then I get an authentication failure.

I speculate that this is some sort of bytes/strings mismatch and my username and password are being sent in some wrong bytes/UTF/? way.  I see the username in the server log with a failure.

As an aside, the xsend.py example needs () around the args to print.

It would be helpful to know if anyone thinks that this works with python 3.

**Comment by D-L** [comment]
try the following patch
```
--- a/xmpp/auth.py
+++ b/xmpp/auth.py
@@ -38,9 +38,10 @@ def H(some):
         some = some.encode("utf-8")
     return md5(some).digest()
 def C(some):
-    if isinstance(some[0], bytes):
-        some = map(str, some)
-    return ':'.join(some)
+    if IS_PYTHON3:
+        some = [ x.encode('utf-8') if isinstance(x,str) else x for x in some ]
+        return b':'.join(some)
+    return ':'.join(map(str,some))
```

**Comment by amotl** [comment]
Dear David,

thank you for this patch. Can I humbly ask you to submit it as a pull request? I will be happy to publish another patch release including it.

With kind regards,
Andreas.

**Comment by sumdog** [comment]
I had someone who uses one of my tools experience the same issue:

https://gitlab.com/djsumdog/dav-xmpp-sync/-/issues/1#note_752958838

I don't have this issue on my own XMPP server running prosidy, but I created an account on chatterboxtown.us which uses ejabberd. I was able to replicate the authentication failure.

```
...
    while not self.set: self._owner.Process(10)
  File "/home/cassius/.local/lib/python3.8/site-packages/xmpp/dispatcher.py", line 129, in Process
    raise ex
  File "/home/cassius/.local/lib/python3.8/site-packages/xmpp/dispatcher.py", line 307, in dispatch
    handler['func'](session,stanza)
  File "/home/cassius/.local/lib/python3.8/site-packages/xmpp/dispatcher.py", line 219, in streamErrorHandler
    raise exc((name,text))
xmpp.protocol.NotAuthorized: ('not-authorized', '')
```

If I manually patched the local xmpppy in my local environment using the code provided by @D-L. Authentication works on both my prosidy server and the chatterbox/ejabberd server. I'm currently on Python 3.8.12.

For now I can monkey patch the issue using the following:

```
import xmpp
import sys

def _C_monkey_patch(some):
    if sys.version_info >= (3, 0, 0):
        some = [ x.encode('utf-8') if isinstance(x,str) else x for x in some ]
        return b':'.join(some)
    return ':'.join(map(str,some))
xmpp.auth.C = _C_monkey_patch
```

I see a PR was never submitted. I could make one. Are there any tests, code formatting checks or CI/CD pipelines in this project? I don't see any.

**Comment by amotl** [comment]
Hi again,

thanks again for the contribution, @D-L. @sumdog submitted your patch with #54 and we just merged it and released xmpppy version 0.6.5 to PyPI.

With kind regards,
Andreas.

**Comment by gdt** [comment]
Thanks all for the fix, submitting it, reviewing and approving.   I just updated locally the pkgsrc entry for xmpppy to 0.6.5, built on NetBSD/9 amd64 with Python 3.9, and confirmed that with my modified xsend.py script, authentication works against ejabberd.

I am finding that xsend.py needs some extra parens in print, but that's very minor and I will try to get a PR filed about that.

**Comment by amotl** [comment]
Dear Greg,

let's just move forward with #55 and remove `xsend.py` altogether, as `xmpp/cli.py` now has all the details and contains the complete canonical implementation to connect, authenticate and submit a single XMPP message.

With kind regards,
Andreas.

**Comment by Neustradamus** [comment]
@sumdog: Can you publish your https://gitlab.com/djsumdog/dav-xmpp-sync on GitHub too?
A mirror?

Thanks in advance!

**Comment by gdt** [comment]
Now that you've merged the authentication file change, that seems viable.  I will try that and open an issue if I have any problems.   Thanks for all the fixes.

**Comment by sumdog** [comment]
> @sumdog: Can you publish your https://gitlab.com/djsumdog/dav-xmpp-sync on GitHub too? A mirror?
> 
> Thanks in advance!

Sorry, I purposefully put all new projects on Gitlab and have been thinking of migrating old projects off Github.  It's pretty trivial to create an account there if you want to submit patches, or I can take patches via e-mail as well.
