### ISSUE TITLE
JID has no node only a domain

### ISSUE THREAD

**Issue by smudge1977** [xmpppy/xmpppy#57]
So I often want to assume `JID('a_process')` or `JID('a_process/resource')` is at my local domain which gets dealt with elsewhere
However `protocol.JID` gives a blank node and sets the domain which is a pain.
So my ugly fix is this at the end of the init of JID

```
        if self.node == '':
            self.node = self.domain
            self.domain = ''
```

```
class Test_JID():
    def test_1(self):
        jid = JID('audiod/Jcop')
        assert jid.getDomain() == ''
        assert jid.getNode() == 'audiod'
        assert jid.getResource() == 'Jcop'

    def test_2(self):
        jid = JID('audiod@ics/Jcop')
        assert jid.getDomain() == 'ics'
        assert jid.getNode() == 'audiod'
        assert jid.getResource() == 'Jcop'

    def test_3(self):
        jid = JID('audiod')
        assert jid.getDomain() == ''
        assert jid.getNode() == 'audiod'
        assert jid.getResource() == ''

    def test_4(self):
        jid = JID('audiod@ics')
        assert jid.getDomain() == 'ics'
        assert jid.getNode() == 'audiod'
        assert jid.getResource() == ''
```

**Comment by smudge1977** [comment]
Can we merge this please?
This is essentially a str JID -> JID object as apposed to where the named arguments are used.
Although this line:
`if not jid and not domain: raise ValueError('JID must contain at least domain name')`
does imply that `myjid = JID(domain='mydomain')` is a valid jid although I can't see in reality how this would ever be a useful jid!!??

The question really is if test_1 is correct to the XMPP specification....:
```    def test_1(self):
        jid = JID('audiod/Jcop')
        assert jid.getDomain() == ''
        assert jid.getNode() == 'audiod'
        assert jid.getResource() == 'Jcop'
```

**Comment by smudge1977** [comment]
> The question really is if test_1 is correct to the XMPP specification....:
> 
> ```
>         jid = JID('audiod/Jcop')
>         assert jid.getDomain() == ''
>         assert jid.getNode() == 'audiod'
>         assert jid.getResource() == 'Jcop'
> ```

I think not :(  [https://xmpp.org/rfcs/rfc3920.html#addressing](https://xmpp.org/rfcs/rfc3920.html#addressing)
"Many other JID types are possible (e.g., <domain/resource> could be a server-side script or service)."

I therefore suggest my change gets retracted and might as well put in the other tests for what they are worth.

**Comment by amotl** [comment]
Hi again,

#62 has the most recent patch to address this issue. However, @smudge1977 asked not to integrate it because it would not fit into mainline. Therefore, I am closing this issue. Feel free to reopen anytime.

With kind regards,
Andreas.
