### ISSUE TITLE
Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by smudge1977** [xmpppy/xmpppy#64]
Your current head 8eb1092 is fine but the 0.7.0 version on PyPi does not work for me on an Ubuntu machine:

`
    return super().auth(username, password, resource)
  File "/home/asl/xmpppy/xmpp/client.py", line 223, in auth
    if xmpp.auth.NonSASL(user,password,resource).PlugIn(self):
  File "/home/asl/xmpppy/xmpp/client.py", line 73, in PlugIn
    if 'plugin' in self.__class__.__dict__: return self.plugin(owner)
  File "/home/asl/xmpppy/xmpp/auth.py", line 71, in plugin
    query.setTagData('digest',sha1(owner.Dispatcher.Stream._document_attrs['id']+self.password).hexdigest())
TypeError: Unicode-objects must be encoded before hashing
`
Could you possible just publish your latest package to PyPi please?
Thanks

**Comment by amotl** [comment]
Dear @smudge1977,

thanks for the reminder. xmpppy 0.7.1 is on PyPI [1,2].

With kind regards,
Andreas.

[1] https://github.com/xmpppy/xmpppy/releases/tag/0.7.1
[2] https://pypi.org/project/xmpppy/
